# Generated by Django 3.1.1 on 2020-10-28 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20201028_0905'),
        ('produtos', '0002_auto_20201028_0837'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
    ]
